<?php

/**
 * PluginAshiato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opAshiatoPlugin
 * @subpackage Ashiato
 * @author     Shingo Yamada <s.yamada@tejimaya.com>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class PluginAshiato extends BaseAshiato
{

}
